[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "freshlens"
version = "0.1"
dependencies = []

[tool.setuptools]
packages = ["module", "backend", "frontend"]
